### ISSUE TITLE
Science keywords linkages

### ISSUE THREAD

**Issue by rwegener2** [NASA-IMPACT/admg-casei#144]
# Overview
ADMG has put a lot of work into curating metadata fields for a variety of science keywords.  The result is that there are several sets of science keywords at different levels of specificity and different types of keywords are linked to different entities in the platform.  We would like to make sure this metadata is leveraged to maximum benefit so this ticket exists to assess where those keywords are used and develop ideas for their effective use.

# Background
There are 4 types of science concepts that ADMG uses in their inventory, which is also summarized [here](https://docs.google.com/document/d/1tJXOyqM5b7iGjTLwWiIDRMeaaVaIH0V8xpafk-jITrE/edit#heading=h.du0r5elpdiz):
1. NASA Earth Science Focus Areas
2. Geophysical Concepts
3. GCMD Phenomena (also called Science Keywords or Measurement Keywords)
4. Focus Phenomena

| Concept  | Total #  |  Defined by |
|---|---|---|
| NASA Earth Science Focus Areas  |  8 | NASA Earth Science Division  |
| Geophysical Concepts |  28 | ADMG  |
|  GCMD Phenomena (also called Science Keywords or Measurement Keywords | ~3000  | NASA's CMR  |
| Focus Phenomena  | unconstrained (infinite number)  | free text entry by ADMG |

The first three are concepts are enumerated fields (there is a set number of them) and they are linked together.  The Focus Phenomena are defined by ADMG without much constraint and will vary quite widely across campaigns.  This ticket is primarily focused on the first three.

The first three concepts are linked together as explained in [this document](https://docs.google.com/document/d/1bthNre9AIgImeluxXlZlpBEJaBZH_oB5y-8N0g153TQ/edit) from ADMG.  To read it you will need to request access.

# Goals
Science concepts are present in the interface in several places:
1. home page (focus areas and geophysical concept boxes which link to the search page)
2. campaign page "Focus" section
3. instruments page "Instrument Details" section

We would also like to consider adding a page or a component to a page which would allow a user to visually explore and understand the different science concepts.

The goal of this ticket is to document and organize ideas which would improve the user's experience with science concepts in the interface.  Initially we would like to focus on the following tasks:
- [ ] how the focus areas and geophysical concepts are listed on the campaigns page
- [ ] how the measurement keywords are listed on the instruments page
- [ ] creating a page or a section of a page where the user can explore the relationships between the different concepts

Each of these is described in more detail below.

# Tasks
### 1) how the focus areas and geophysical concepts are listed on the campaigns page
On the campaigns page the focus areas and geophysical concepts are listed as just a comma seperated list of strings:
<img width="600" alt="Screen Shot 2020-10-12 at 4 52 34 PM" src="https://user-images.githubusercontent.com/35503632/95796908-57fbe900-0cab-11eb-8022-b47e8f65d102.png">
How can we better display this information to help the user more easily skim what type of data is collected?  One component may be to show the relationship between the focus areas and the geophysical concepts because it would help the user zoom more quickly to the large concept (the focus area) and then look more specifically at the related geophysical concepts.

### 2) how the measurement keywords (GCMD Phenomena) are listed on the instruments page
Measurement keywords are listed on the instruments page as a comma separated list.  There are two goals to improve in this section:
1. display the hierarchy of the keywords

As can be explored in [this doc](https://docs.google.com/spreadsheets/d/1NDL8mF5od8idxy6FJdUA2vh-akXYeyBRg_ZT05D0wEY/edit?userstoinvite=rachel@developmentseed.org&ts=5ede5a92&actionButton=1#gid=0) keywords are organized in an hierarchy by category > topic > term > variable level 1 > variable level 2 > variable level 3.  Most keywords don't get specified all the way to variable level 3.  That document also shows the mapping from geophysical concept to measurement keywords.
 
<img width="600" alt="Screen Shot 2020-10-12 at 5 04 29 PM" src="https://user-images.githubusercontent.com/35503632/95797543-00f71380-0cad-11eb-8491-f5239f105a80.png">

I'm not totally sure what we are currently displaying in the interface but I think we'd like to change the display to allow users to more easily skim the keywords.

2. [maybe] relate the keywords to their associated geophysical concepts (mapping in [this doc](https://docs.google.com/spreadsheets/d/1NDL8mF5od8idxy6FJdUA2vh-akXYeyBRg_ZT05D0wEY/edit?userstoinvite=rachel@developmentseed.org&ts=5ede5a92&actionButton=1#gid=0) , also linked in point 1)

It may or may not also be helpful to add some small component or have as a part of visual showing how the measurement keywords are related to geophysical concepts.  Or maybe it isn't.  🤷‍♀️ 

### 3) creating a page or a section of a page where the user can explore the relationships between the different concepts

The final way we may want to help the user understand the science concepts is to design a page that allows them to understand the relationship between the entities.  The goals of this page (or pages or part of a page) would be:

1. Define the difference between focus areas, geophysical concepts, and GCMD phenomena
2. View the relationships between each of the science concepts
3. (maybe) browse entities by concepts or groups of concepts

If we looked into number 3 we may consider how that would tie into the search view or not.  This relates to the larger goal of defining how this type of visual or interactive content would fit in the user flow.

**What we have so far**
![ADMG Inventory - Inter-related Science Concepts](https://user-images.githubusercontent.com/35503632/95798270-b8d8f080-0cae-11eb-83d3-bd89fed0072a.jpg)

**Prior Brainstorming**
Some brainstorming of visuals that we have already done include:
Hierarchy Visuals
<img width="350" alt="Screenshot 2020-09-22 at 16 50 26" src="https://user-images.githubusercontent.com/35503632/95798493-5e8c5f80-0caf-11eb-9129-f37fc8980b14.png">

<img width="350" alt="Screenshot 2020-09-22 at 16 50 26" src="https://user-images.githubusercontent.com/35503632/95798218-93e47d80-0cae-11eb-9f91-8b8c3a82f22e.png">

Network Visuals
<img width="350" alt="Screenshot 2020-09-22 at 16 50 26" src="https://user-images.githubusercontent.com/35503632/95798227-9a72f500-0cae-11eb-9ab2-1290d07b5934.png">

<img width="350" alt="Screenshot 2020-09-22 at 16 50 26" src="https://user-images.githubusercontent.com/35503632/95798232-9fd03f80-0cae-11eb-8464-0150ece9f46f.png">

While these were good for brainstorming it is important to remember that the entity relationships are many to many.
