### ISSUE TITLE
Fallback images

### ISSUE THREAD

**Issue by tania-pires** [NASA-IMPACT/admg-casei#162]
## Stage 1 - This ticket
One icon per entity.
- [x] generic instrument image
- [x] generic platform image
- [x] generic campaign logo image

## Stage 2 - Future
One icon for campaign.  One icon per parent group for Platforms.  One icon per "type" (what that means TBD) for Instruments.
TODO get list of parent groups for Platforms.
