### ISSUE TITLE
EPIC: Add Google Analytics to CASEI

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/admg-casei#419]
# Description
As we start thinking about userflow on CASEI and understanding where our users come from, it could be very useful to have google analytics fully implemented on the site. 
This should allow us to see how users click through the links on our pages, and potentially other detailed metrics that we might care about. 

# Task List
- [ ] Understand what capabilities google analytics can provide
- [ ] Clarify exactly which elements we need to track
- [ ] Setup google analytics on the site
