### ISSUE TITLE
EPIC: Port E2E test suite over to Playwright and implement local visual regression testing

### ISSUE THREAD

**Issue by edkeeble** [NASA-IMPACT/admg-casei#457]
**Is your feature request related to a problem? Please describe.**
Coming out of the [visual testing ADR](https://github.com/NASA-IMPACT/admg-casei/blob/develop/docs/adr/0004-visual-testing.md), there is a need to implement local (and CI-based) visual regression testing on a variety of platforms for the benefit of developers.

**Describe the solution you'd like**

- [x] Port E2E test suite from Cypress to Playwright
- [x] Add a VRT snapshot to each page tested by Playwright across all popular desktop platforms and iOS (Safari) and Android (Chrome)
- [x] Add a GitHub Action to run the new E2E test suite
