### ISSUE TITLE
EPIC: Create Data Products View

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#489]
## Problem
There is no straightforward way to access data products on CASEI. This was feedback from an airborne workshop around accessing data products from CASEI quickly, without needing to first find a campaign. 

In the current state you can only find this data products information when inside of a campaign page:
![image](https://user-images.githubusercontent.com/10764915/212715902-f2de47d4-42cc-498a-b57c-451dd4057316.png)

There is an opportunity for CASEI to improve Data Products discovery within the interface.

## Goal
Help airborne scientists more quickly discover NASA data products within CASEI based on a variety of variables, instead of only through campaigns, platforms and instruments.

As a user, I want to filter data products w/o first selecting a campaign/platform/instrument so that I can more quickly access the products I need.

## Interviews
[Research report](https://docs.google.com/presentation/d/18_xcyq3N3l848p-RibOd6mYs8iaD4hCq_kE7cfPQSnY/edit#slide=id.gb700de37bd_0_149)

## Initial Designs for Non-Beta Release (see [Figma mockup](https://www.figma.com/proto/KGRSOFMlERgOSK2t5pIYXD/Data-Products-View?page-id=204%3A4467&node-id=204-4468&viewport=772%2C616%2C1&scaling=min-zoom&starting-point-node-id=204%3A4468&show-proto-sidebar=1))
![image](https://github.com/NASA-IMPACT/admg-casei/assets/10764915/8d569ee5-b77a-48d1-a035-295ac98b561c)

## Process
- [x] Problem Discovery - diving deeper into the problem
- [x] Design Exploration
- [x] User Testing https://github.com/NASA-IMPACT/admg-casei/issues/496
- [x] Refinement of designs ([Figma mockup](https://www.figma.com/proto/KGRSOFMlERgOSK2t5pIYXD/Data-Products-View?page-id=204%3A4467&node-id=204-4468&viewport=772%2C616%2C1&scaling=min-zoom&starting-point-node-id=204%3A4468&show-proto-sidebar=1))
- [x] Implementation of Solution (Development)
- [x] Have a version of this conceptualized and at least ready for testing/staging (Development)
