### ISSUE TITLE
EPIC: Visualize aircraft flight path for 5 Campaigns in CASEI

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#576]
This is an epic level issue that provides context and tasks to track progress. Separate issues will be linked based on sprints.

# Problem

## Feature Context
CASEI is an inventory of NASA’s airborne and field campaigns for Earth Science where scientists can look for metadata across four main categories even though they are also interconnected: campaigns, platforms, instruments, and data products (most recently added). This feature focuses on **platforms**, which are stationary or non-stationary structures like aircraft, balloons, field sites, vehicles, ships, and buoys that carry instruments. There are many types of platforms but at a high level they are either stationary (with a lon/lat) or non-stationary (series of lon/lats creating a path). 

<img width="624" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/748b7a00-5eb6-42f5-a671-ddbd0a3f78ac">

- **Aircrafts** - Planes that move and have flight tracks/paths and elevation. Could also include balloons. Most interesting visually as the routes can be regional or cover large areas.
- **Mobile land-based** - Trucks, cars, and/or vans with instruments mounted on them (E.g. [Campaign V](https://impact.earthdata.nasa.gov/casei/platform/Campaign%20V))
- **Water-based stations** - Some move (ships, underwater vehicles, uncrewed surface vehicle, saildrone, research vessel), others are stationary (water sites, buoys)
- **Stationary land sites** - These are field or land sites that have a location but do not move

## Current State
Currently in CASEI, we portray platforms through images, descriptions, links, and associations to other metadata both as its own feature page on the website, as well as in the associated campaigns and instrument pages. 

Below is an image of a campaign page for [IMPACTS](https://impact.earthdata.nasa.gov/casei/campaign/IMPACTS). The cover image shows a bounding box over the area of campaign deployments, but we do not show the actual moving path or static location of the platform used in that deployment.
<img width="467" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/a8fb1e36-041f-4092-b3f9-a8f72c8c2002">

Additionally, each campaign page has an interactive timeline showing the different campaign deployment periods, but it only focuses on the timeframe without details about the actual deployed platforms.
<img width="1202" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/e0de0095-06cb-47f0-8a59-c32162677f6b">

## Problem/Opportunity
Even though airborne data is spatial, CASEI does not currently highlight the spatial aspects of the data as well as it could in order to support metadata discovery. We showcase the spatial bounds of a field campaign, but without any other detail. In particular, campaign platforms like aircrafts have  flight paths that could be showcased to allow scientists to better see and explore data (and areas) of interest.

<img width="181" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/1bfdcd3a-e77a-49fd-b9ea-99655ba388da"> ✅ We currently show the spatial bounds of platform deployments on a campaign page
<img width="179" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/1bd5e530-3eac-4b9c-9c94-0c1ef6c87e0a"> ✅ We also list the names and show images of the platforms associated with a campaign
<img width="178" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/d4f087d9-523b-45f8-964c-ca7d6465e05e"> ❌ But we don’t show the actual moving path or stationary location of any platform

**Use Case** - When scientists are looking at a campaign, they would have an enhanced view of each deployment by seeing precisely where a plane traveled throughout the field investigation.

### How might we give airborne scientists the ability to see the flight path of an aircraft platform for a given deployment within a Campaign page?

---------------

# Objective

## Key Requirements
- Show the flight path for all aircrafts we can access data for (altitude and time are nice to explore but not priority)
- If a deployment has multiple platforms, show multiple flight paths on a map. Some deployments will have 1 platform, others might have multiple
- If a deployment has aircrafts with overlapping paths, show that there are overlapping paths.
- If platform tracks are for the same deployment, set map default to show different geographic scopes (one covers Atlantic ocean, another is regional)
- Legend or way to know what platform corresponds with the path
- Provide a way to turn the path flight path layers on and off

## Key Considerations
- **Data access** - Stephanie will need to support us in getting flight data for aircrafts. Flight tracks data should be available either through a NASA DAAC (Distributed Active Archive Center) or the [airborne science program](https://airbornescience.nasa.gov/). But currently this isn’t in CASEI. Of the 276 deployments listed [here](https://admg.nasa-impact.net/api/deployment), none have flight path information. We can programmatically check which platforms have flight_tracks attributes values, however, this points to a URL. Eg. The [KORUS-AQ](https://impact.earthdata.nasa.gov/casei/campaign/KORUS-AQ) campaign has platforms that do have flight tracks but they are logged on the [DAAC website](https://www-air.larc.nasa.gov/missions/korus-aq/DC8-Plotter.html).
- If we cannot access data for all aircrafts, we need to consider what that UI experience will be like for missing data.
- **No maintenance interface enhancements** - Given we gather data on aircrafts and other platforms, we will NOT support an MI enhancement to allow curators to input this themselves as part of curation.

## Indicative Sketch of Desired Outcome
![flight paths feature](https://github.com/NASA-IMPACT/admg-casei/assets/10764915/91f961e7-2925-4055-800f-6df83251a4f6)

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/414
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/577
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/579
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/578
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/581
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/580
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/582
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/583
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/584
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/585
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/590
```
