### ISSUE TITLE
Design refinement for flight paths - legend display

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#611]
## Goal
The purpose of this issue is to minimally iterate on the visual design on the flight paths feature to help improve the clarity of the legend display

## Acceptance Criteria
- Proposed visual designs that are signed off for small improvements to the flight maps
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/615
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/616
- [ ] https://github.com/NASA-IMPACT/admg-casei/issues/617
```

**Comment by heidimok** [comment]
## Design Update March 21

- I explored some of the initial feedback brought up by Stephanie in January when we first released flight maps. I'm documenting the progress and process because each of the potential changes will likely spin off into sub issues.

### **Situation:** We were not able to get nav data for a platform
**Solution:** Show it, but disable interaction functionality. Add text like "Not Shown"
![image](https://github.com/NASA-IMPACT/admg-casei/assets/10764915/f35b447c-5c09-4fa1-ab53-2945d2c1d4ff)

### **Situation:** Upon selecting a deployment (assuming more than 1), a platform is not operating at that time.
**Solution:** We still show the platform name, but disable functionality to interact. Add text like "Not Operating"
<img width="906" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/32950c1d-0225-4d89-a465-02da4e2ad894">

### **Situation:** Some platform names aren't meaningful or descriptive, and this makes the legend items unclear
**Solution:** This is more of a curator goal to rename some of the platform short names, particularly stationary ones, to be more descriptive. By changing the short name, it should automatically make the legend here more clear AND improve the names across CASEI. 
<img width="446" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/6e8f6212-bb7a-4fe3-a4b8-1ab9f7ee541a">

### Situation: Differentiating between platforms. Right now they are all green and get confused with the deployments below. This was actually the design intention but perhaps it's more confusing to conflate them.
**Solution:** We can try assigning different colors to platforms
<img width="1116" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/2b975c61-609f-4dc8-aac9-30b48a987f78">

**Comment by heidimok** [comment]
Tasks/issues have been created. We will move this to the next PI and start focusing on the development side. Link to Figma: https://www.figma.com/file/Xdvl5YREinOq8E5kMcJnK9/Campaign-flight-maps-UI-feature?type=design&node-id=259-552&mode=design
